### ISSUE TITLE
CSS does not load on https://partytown.builder.io/ with ad-blocker

### ISSUE THREAD

**Issue by homburg** [BuilderIO/partytown#124]
When using the chrome ghostery ad-blocker: https://chrome.google.com/webstore/detail/ghostery-%E2%80%93-privacy-ad-blo/mlomiejdfkolichcflejclcbmpeaniij?hl=en the site looks like this

![Screenshot 2022-03-22 at 09 41 05](https://user-images.githubusercontent.com/235886/159441861-be3b6095-768f-4061-b6ac-ea5310e390e8.png)

**Comment by Linux123123** [comment]
It's because `css` file is named `google-tag-manager.c9a8d230.css` and your adblocker matches any file that has `google-tag-manager` in it's name.

**Comment by adamdbradley** [comment]
Thanks for debugging that @Linux123123. I'll see if I can update the site to not pull in that filename into the css.

**Comment by adamdbradley** [comment]
Fixed with Astro 0.26. Thanks @FredKSchott!
