### ISSUE TITLE
Is Partydown compatible with Gatsby's Segment plugin?

### ISSUE THREAD

**Issue by kilinkis** [BuilderIO/partytown#126]
Hi guys!
Congrats on Partydown, is such a cool tool!

I'm wondering if it is compatible with this plugin: 
https://www.gatsbyjs.com/plugins/gatsby-plugin-segment-js/

This plugin injects Segment's snippet for us, and has several options.
I wonder if it can work together with Partydown or if Partydown needs the actual html snippet.

Thanks in advance!

**Comment by adamdbradley** [comment]
Sorry but at this time we're not sure if Partytown is compatible with this service. Would you be able to create a PR which tests this service with a minimal amount of code? A good example to emulate is the Google Tag Manager test: https://github.com/BuilderIO/partytown/tree/main/tests/integrations/gtm

In this case, just testing segment itself would be fine.

Some more information can be found here: https://github.com/BuilderIO/partytown/blob/main/DEVELOPER.md#plugin-authors--developers

Thank you for your help!
