### ISSUE TITLE
How to use with NuxtJS v2?

### ISSUE THREAD

**Issue by itsmnthn** [BuilderIO/partytown#135]
There is `@nuxtjs/partytown` plugin for Nuxt3 and Nuxt-Bridge.

**Comment by adamdbradley** [comment]
Sorry but this I think this question is better asked in either [Github Discussions](https://github.com/BuilderIO/partytown/discussions) or [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.
