### ISSUE TITLE
Vite wrong file path with debug mode

### ISSUE THREAD

**Issue by xesjkeee** [BuilderIO/partytown#151]
Hey, thanks for the partytown!

After some time of usage, I faced with the error:

My `vite.config.ts`
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path'
import { partytownVite } from '@builder.io/partytown/utils'

export default defineConfig({
    plugins: [
        partytownVite({
            dest: path.join(__dirname, 'dist', 'partytown')
        }),
        vue(),
        // ...
    ]
})
```

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- meta elements -->
  
    <script>
      partytown = {
        debug: true,
        lib: '/partytown/'
      }
    </script>
    <script src="/partytown/partytown.js"></script>

    <script type="text/partytown">
        // analytics script
     </script>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
```

While `partytown.debug == false` there are all good, but when I set `true`, I get the error in the devtools: 
```
GET https://localhost:8080/partytown/debug/partytown-sandbox-sw.js?v=0.5.2 net::ERR_ABORTED 404 (Not Found)
```

Let's open this link in the new tab, and yeah – "Page not found", but if I remove query params from the link `?v=0.5.2` and try to go again, I'll get the needed file

<img width="1046" alt="img" src="https://user-images.githubusercontent.com/17751886/162566782-5f31ae68-31b5-4ccf-acf0-4228cd3bb429.png">

**Comment by xesjkeee** [comment]
Thanks for @Fl0pZz, his [PR](https://github.com/BuilderIO/partytown/pull/152) should fix it

Just copied his fixes directly to `node_modules/@builder.io/partytown/utils/index.cjs` to check it, and I got successfully working vite-server with partytown:

![img](https://user-images.githubusercontent.com/17751886/162575211-4604fa4c-2091-466f-a8bc-7e3239b7e0ac.jpg)

![img](https://user-images.githubusercontent.com/17751886/162575227-5a95ded9-129f-4d21-b56e-7f7830be8821.jpg)

![img](https://user-images.githubusercontent.com/17751886/162575240-c0882fff-3b79-46b8-ae7f-23b0797218f7.jpg)

**Comment by adamdbradley** [comment]
Should be fixed with https://github.com/BuilderIO/partytown/commit/d2f68408bdb8b0b526349dba2ecf0ed4dd62085c
