### ISSUE TITLE
How to find the forward config for a service? (Pendo)

### ISSUE THREAD

**Issue by soyzamudio** [BuilderIO/partytown#156]
I'm going to be implementing partytown to our platform and i'm trying to move pendo to partytown, but can't seem to find what to put in for the forward config, any help?

this is what the script looks like:

```
      (function (apiKey) {
        (function (p, e, n, d, o) {
          var v, w, x, y, z;
          o = p[d] = p[d] || {};
          o._q = [];
          v = ['initialize', 'identify', 'updateOptions', 'pageLoad'];
          for (w = 0, x = v.length; w < x; ++w)
            (function (m) {
              o[m] =
                o[m] ||
                function () {
                  o._qm === v[0] ? 'unshift' : 'push';
                };
            })(v[w]);
          y = e.createElement(n);
          y.async = !0;
          y.src = 'https://cdn.pendo.io/agent/static/' + apiKey + '/pendo.js';
          z = e.getElementsByTagName(n)[0];
          z.parentNode.insertBefore(y, z);
        })(window, document, 'script', 'pendo');
      })(API_KEY);
```

**Comment by adamdbradley** [comment]
Sorry there's really no one-size fits all solution, since each third party script uses different variables in different ways.

I'm assuming the pendo documentation lists the methods you can call on their `window.pendo` object. Just glancing at this it looks like `pendo._q` and `pendo._qm` may be what you're looking for. 

If you're able to get it working, would you be able to submit an edit that adds pendo to this list? https://partytown.builder.io/common-services

Thanks

**Comment by codeithuman** [comment]
@soyzamudio, any update on this by chance? We're looking to do this as well.

**Comment by codeithuman** [comment]
I was able to get Pendo installed with Partytown, but then would have had to set up a reverse proxy for the script that's loaded when opening Pendo's Designer tool. I decided I didn't want to set up a reverse proxy on Netlify then, so I ultimately chose to install the Pendo script without Partytown.

For those interested my Partytown code with looking like the following before I chose to ditch Partytown:

```html
<head>

<!-- Partytown config -->
<script>
  partytown = {
    resolveUrl: function (url, location, type) {
      if (type === 'script') {
        var proxyUrl = new URL('https://app.pendo.io/in-app-designer/latest/communication.html');
        proxyUrl.searchParams.append('url', url.href);
        return proxyUrl;
      }
      return url;
    },
    forward: ["pendo"]
  }
</script>
<!-- END Partytown config -->

<!-- Pendo -->
<script>
  (function(apiKey){
    (function(p,e,n,d,o){var v,w,x,y,z;o=p[d]=p[d]||{};o._q=o._q||[];
    v=['initialize','identify','updateOptions','pageLoad','track'];
    for(w=0,x=v.length;w<x;++w)(function(m){o[m]=o[m]||function(){o._q[m===v[0]?'unshift':'push']([m].concat([].slice.call(arguments,0)));};})(v[w]);
      y=e.createElement(n);
      y.async=!0;
      y.src='https://cdn.pendo.io/agent/static/'+apiKey+'/pendo.js';
      z=e.getElementsByTagName(n)[0];z.parentNode.insertBefore(y,z);})(window,document,'script','pendo');

      pendo.initialize({});
  })("<%= process.env.PENDO_API_KEY %>");
</script>
<!-- END Pendo -->
</head>
```

I'm not 100% sure the `resolveUrl` code in the Partytown config section is correct. I added it when I learned I needed to set up a Reverse Proxy on Netlify and then decided to not install Pendo with Partytown.
