### ISSUE TITLE
How to use Partytown to load GTM on NextJS

### ISSUE THREAD

**Issue by RigottiG** [BuilderIO/partytown#157]
I'm trying to use worker strategy to load third party scripts, but it doesn't work properly. I follow the docs and set `nextScriptWorkers: true` flag in next.config.js, install `partytown` when requested, and set by third-party script strategy to worker, but it seems doesn't work. Nothing appears on console or network tab.

**_app.ts**
```javascript
 <Script
     strategy="worker"
     id="gtm"
     dangerouslySetInnerHTML={{
      __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl+'&gtm_auth=${process.env.NEXT_PUBLIC_GTM_AUTH}&gtm_preview=${process.env.NEXT_PUBLIC_GTM_PREVIEW}&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','${process.env.NEXT_PUBLIC_GTM_ID}');`,
      }}
   />
```

**Comment by Abhishek765Flyfin** [comment]
@RigottiG is your problem resolved??

**Comment by meck93** [comment]
@RigottiG i think you should ask this question in the Next.js repository (issues/discussions) since it concerns the Next.js specific implementation/integration of partytown.

**Comment by viictorcamposs** [comment]
Hey @RigottiG your problem is that the Script component provided by Next.js doesn't work with "worker" strategy when it's inline script. You can check it out in the Next.js' doc: https://nextjs.org/docs/basic-features/script
