### ISSUE TITLE
Missing partytown-sandbox-sw.html?

### ISSUE THREAD

**Issue by michaelwu0505** [BuilderIO/partytown#163]
In developer console, I was seeing file not found for "partytown-sandbox-sw.html".

In source code, there is a line that looks like this:
`sandbox.src = libPath + "partytown-" + (isAtomics ? "atomics.js?v=0.5.2" : "sandbox-sw.html?" + Date.now());`

I can find the file on builde.io web site:
[https://www.builder.io/c/~partytown/debug/partytown-sandbox-sw.html](https://www.builder.io/c/~partytown/debug/partytown-sandbox-sw.html)

Its content is:
`<!DOCTYPE html><html><head><meta charset="utf-8"><script src="./partytown-sandbox-sw.js"></script></head></html>`

However, I don't seem to be able to find it on github repository nor in documentation. Am I missing something?

Thanks.

**Comment by michaelwu0505** [comment]
I've found the documentation regarding partytown-sandbox-sw.html:
[https://partytown.builder.io/distribution](https://partytown.builder.io/distribution)

Closing this issue. Thanks.

**Comment by hiepxanh** [comment]
how do you solve that? I still cannot understand the explain in the docs?
