### ISSUE TITLE
Can't pass callback to worker functions

### ISSUE THREAD

**Issue by lebreRafael** [BuilderIO/partytown#167]
The [docs](https://partytown.builder.io/how-does-partytown-work#serialization) are saying that we can pass functions between worker and main thread, but looks like this is only true on one side. I can pass a callback from **Worker to Main Thread** but I can not pass it from **Main Thread to Worker**.

Here is the code I used to test  _(disregard the timeout. I used it only to prevent race conditions)_
```
const testScript = `
  window.analytics = [];
  window.analytics.track = (title, cb) => {
    console.log('Logging analytics.track arguments', {title, cb});
    cb();
  };
  window.addEventListener('click', () => {
    console.log('Worker > Main Thread callback')
  });
`;
```
```
<script
  dangerouslySetInnerHTML={{
    __html: `
      setTimeout(() => {
        window.analytics.track('My event', () => {
          console.log('Main Thread > Worker callback')
        });
      }, 3000);
      partytown = {
        forward: ['analytics.track'],
      };
    `,
  }}
/>
<script type="text/partytown" dangerouslySetInnerHTML={{__html: testScript}}/>
```

And this are the logs I see in the browser after reloading the page and clicking
<img width="559" alt="Screen Shot 2022-04-29 at 6 15 03 PM" src="https://user-images.githubusercontent.com/13899924/166070118-19e28e3a-8930-4ce4-9602-29f4278f0222.png">

As we can see the Main **Thread > Worker callback** never shows and we can see that the callback is an empty function inside the worker.

**Comment by lebreRafael** [comment]
If the maintainers says that this could be implemented I could try to work on this

**Comment by adamdbradley** [comment]
Sorry no, I'm not sure this scenario would be possible.

**Comment by steve8708** [comment]
I wonder if this could be possible by supporting only isolated functions and stringifying them to send

e.g. kinda like puppeteer does, like you can't reference vars outside of the function body scope, but we could pass it to the worker thread as a string and eval it there

**Comment by lebreRafael** [comment]
Hmm that would work for my scenario.
Let me know if you guys agree this can be implemented and if you wanna me to contribute on this implementation.

Just to clarify, here is my scenario:
I have a link but I can not redirect the page right away when user clicks it because I could miss the analytics (Segment) tracking event, so I need to do the redirect in the callback and it will run after the event is sent.

**Comment by steve8708** [comment]
Very cool. If you're game to take a stab at it and send a PR that passes build and adds an additional test for this, that would be great

**Comment by cameronbraid** [comment]
I need something like this.
