### ISSUE TITLE
Deprecated APIs in use (GTM)

### ISSUE THREAD

**Issue by tlgimenes** [BuilderIO/partytown#178]
Hi folks,

I'm using Partytown on a Next.JS project for running Google Tag Manager.  This works great, however, recently, lighthouse started reporting the following error:

![image](https://user-images.githubusercontent.com/1753396/167917064-e1e07f36-5c27-40ed-894b-ddf4a77a8bdf.png)

Also, I'm getting this report on Chrome's DevTools. 

This error only happens when I use Partytown + Google Tag Manager. Using GTM script directly on the main thread does not trigger this error. I tried to see if we use this API on partytown but could not find anything. 

Anyone with any clue on this error? Thanks!

**Comment by jasonRufus** [comment]
I am seeing the same issue using next.js implementation for GTM

**Comment by MarlonPassos-git** [comment]
@jasonRufus  I'm having the same problem with an application in gatsby. How did you enable this setting in atomics?

**Comment by jasonRufus** [comment]
Sorry seems i was mistaken, i have retested and the same error occurs when using atomics.
@MarlonPassos-git but to answer your question, your site needs to be cross origin isolated. you do this by adding these 2 response headers:
Cross-Origin-Embedder-Policy: credentialless
Cross-Origin-Opener-Policy: same-origin
Partytown will automatically use atomics if set.
See more here: https://partytown.builder.io/atomics#document-response-headers
