### ISSUE TITLE
Test Partytown in Cypress

### ISSUE THREAD

**Issue by tyhopp** [BuilderIO/partytown#179]
Hi @adamdbradley, thanks for the great library.

We are integrating Partytown into [Gatsby's new script component](https://github.com/gatsbyjs/gatsby/pull/35403) and one issue we've encountered is testing Partytown usage in [Cypress](https://github.com/cypress-io/cypress).

The Partytown snippet hits [this code path](https://github.com/BuilderIO/partytown/blob/main/src/lib/main/snippet.ts#L34-L36), dispatching an event that `registerWindow` in the sandbox listens for but never receives.

Is there anything else we need to do to generally to make Partytown work in Cypress?

**Comment by tyhopp** [comment]
Created a reproduction, turns out Partytown works fine in an iframe but does not work in Cypress' iframe.

https://github.com/tyhopp/partytown-cypress-reproduction

This isn't exactly a concern of the Partytown library itself since Cypress is a separate tool, but given its widespread usage it would be great if you could provide some direction on this. I doubt we'll be the only ones trying to test Partytown in Cypress.

Thank you!

**Comment by steve8708** [comment]
Ah yes great find, I would suggest filing an issue with Cypress for this as it appears to be an issue on that side as opposed to for Paryttown directly. If you believe I am wrong though, feel free to reopen this

**Comment by tyhopp** [comment]
Hi @steve8708, I revisited this again and wasn't able to use Partytown successfully in an iframe. Here's a reproduction - https://github.com/tyhopp/partytown-iframe-reproduction. Is there something I'm missing? I wasn't able to find a test for this specific case to copy

**Comment by TheFedaikin** [comment]
Can confirm it's not working within iframe - was using it with proprietary analytics. The reproduction above looks right to me and it highlights the issue, but if needed I can make another one.
