### ISSUE TITLE
[bug] get 404 not found ~partytown/debug/partytown-sandbox-sw.html with simple  angular bundle html file and express server

### ISSUE THREAD

**Issue by hiepxanh** [BuilderIO/partytown#193]
**Describe the bug**
Hi, nice to meet you. I see your team's videos on twitter and it so amazing. The other framework tutorial is very good. But I want to try on html example to implement on my Angular app. I do it with basic html and express example but it just not work. and get error.
- the first load is fine
- the second load is error: partytown.js:42 GET http://localhost:3000/~partytown/debug/partytown-sandbox-sw.html?1653750131269 404 (Not Found)

**To Reproduce**
the partytown folder was copied by script, I just copy it again to this public folder.

1. clone https://github.com/hiepxanh/partytown-example
2. `npm install` then `node server-html.js` => should work fine, but `node server-angular.js`
3. open incognito: first load work
4. f5 to reload. See error

**Reproduction link**
my stackblitz here but I have cors problem on stackbitz server https://stackblitz.com/github/hiepxanh/partytown-example?file=server.js

**Expected behavior**
it should not error

**Partytown version**
What version of Partytown you are using, e.g. `0.0.6`

**Screenshots**
![image](https://user-images.githubusercontent.com/16970990/170848604-a6bc152f-bbfd-4bfd-8b19-22f40b1f699c.png)

```.ts
const express = require('express')
var cors = require('cors')
var app = express()

app.use(cors())

const port = 3000

const myLogger = function (req, res, next) {
  console.log('logger:', req.originalUrl)
  next()
}

app.use(myLogger)

app.use(express.static('public'))

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

![image](https://user-images.githubusercontent.com/16970990/170848841-3a66ac00-5339-4df1-b328-a87e00366243.png)

**Additional context**
I read this but doesn't help 

https://partytown.builder.io/distribution#builderiopartytownlib

Also this issue doesn't help too https://github.com/BuilderIO/partytown/issues/107

**Comment by hiepxanh** [comment]
ok I guest problem it self is angular, here is the partytown html version, it work great 
![image](https://user-images.githubusercontent.com/16970990/170859457-7f51c2ca-3d4a-4eec-8c55-7d40776c8115.png)
but the angular version
- the same partytown version
- the same patytown insert code
- run first time, second time is error
- so weird...
![image](https://user-images.githubusercontent.com/16970990/170859498-3e8b465e-09aa-4170-ba26-3cf3d201ba6b.png)
![image](https://user-images.githubusercontent.com/16970990/170859574-06f049eb-f837-445d-8c4d-a1814bff17ad.png)

**Comment by hiepxanh** [comment]
here is angular project if you interest https://github.com/hiepxanh/clover-error
here is the video that i record https://drive.google.com/file/d/1UBokM5xuRr44gftJ70Sft6WwnQTr_T1W/view?usp=sharing
I wonder how should we fix the problem, I should create angular issue or partytown issue?

**Comment by hiepxanh** [comment]
please help me...

**Comment by nicksrandall** [comment]
I'm seeing this issue with React version as well

**Comment by mhevery** [comment]
Hey @hiepxanh ,
Let me see if I understand:
1st request it works
2nd request on page refresh it 404s. 

Do you see any additional errors?

**Comment by hiepxanh** [comment]
I dont see anything else sir, first time I thought server false but it server correctly, just auto fail on second query

**Comment by hiepxanh** [comment]
@mhevery  do you have any suggestions? I can do anything like a test or debug, or something, I love this library very much. but I need your guidance. I will do anything you need sir

**Comment by mhevery** [comment]
One thing you can help is to make sure that the reproduction application is as small as possible. That makes our life easier in pinpointing the issue. (We are a bit busy with relate project so it may take some time to get to this.)

**Comment by hiepxanh** [comment]
Yes sir, I already pushed the built version of angular here.
 ![image](https://user-images.githubusercontent.com/16970990/176563005-f9ea099c-5240-4c73-ad94-eb8e3c1131a7.png)
https://github.com/hiepxanh/partytown-example
I think it may be the angular itself have some block on the service worker which fails on the second request. I will try to reproduce on Angular 14 today

**Comment by adamdbradley** [comment]
Sorry but this issue seems related to Angular and copying files to the correct location, and not partytown itself. https://partytown.builder.io/angular
