### ISSUE TITLE
Is it possible to use Partytown with a shopify 2.0 theme?

### ISSUE THREAD

**Issue by lorenz-himbeermedia** [BuilderIO/partytown#196]
**Describe the bug**
Currently I am trying to integrate partytown to an shopify 2.0 theme.
It is possible to load the partytown scripts from the asset folder and set the path to these scripts in the partytown configuration.

The problem then is, that the shopify cdn and the page are having different urls (shop url and cdn.shopify.com).

I there any way to integrate the partytown functionality manually on a shopify 2.0 theme?

**Comment by mhevery** [comment]
Service workers require that they are on the same URL. See https://partytown.builder.io/shopify-hydrogen

**Comment by christopherdeanfinc3** [comment]
Is it now possible with the Changes to Asset URLs from Shopify? ([Shopify Changelog](https://changelog.shopify.com/posts/changes-to-asset-urls))

 @mhevery / @lorenz-himbeermedia

**Comment by shawnsan-apollo** [comment]
Wanted to follow up on this with this. With the change that @christopherdeanfinc3 mentioned is this now possible?

**Comment by Andi365** [comment]
Any news on this one?

**Comment by j0Shi82** [comment]
> Any news on this one?

Hoping to be able to provide something rather sooner than later: https://github.com/BuilderIO/partytown/issues/405#issuecomment-1788089625
