### ISSUE TITLE
Get Partytown to Beta Status

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/partytown#21]
## Overall Goal

Have Partytown in production and we can collect performance metrics so that we can write use-case studies.

## Criterion for when done:
- [x] GTM works with Partytown
   - [ ] GTM is running in production on builder.io all sites
- [ ] HubSpot integration
  - [ ] HubSpot running in production
- [ ] Intercom integration
  - [ ] Intercom running in production
- [ ] https://www.webpagetest.org/ testing
- [ ] Platform APIs
  - [x] Implement HTML constructor names on the global 0a018c298bb1d593d020e2eaae42c132c0cb3238
  - [x] MutationObserver 09ed37b8feeb0dab1c9302c866b416a1c344c27a
  - [x] IntersectionObserver
  - [x] #23
  - [ ] #25 
- [ ] #10

**Comment by rememberlenny** [comment]
Thank you for tracking this.
