### ISSUE TITLE
Error: Cannot find module '../integration/index.MODULE_EXT'

### ISSUE THREAD

**Issue by jacobwise** [BuilderIO/partytown#22]
Steps to reproduce:

1. [Clone this project](https://github.com/jacobwise/nextjs-partytown)
2. `npm install`
3. `npm run dev`

NPM `7.23.0`
Node `v14.8.0`

Error output:

`error - Error: Cannot find module '../integration/index.MODULE_EXT'
Require stack:
- /Users/jacobwise/Next/partytown-test/node_modules/@builder.io/partytown/react/index.cjs
- /Users/jacobwise/Next/partytown-test/.next/server/pages/_document.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/require.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/load-components.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/api-utils.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/next-server.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/next.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/lib/start-server.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/cli/next-dev.js
- /Users/jacobwise/Next/partytown-test/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.mod._resolveFilename (/Users/jacobwise/Next/partytown-test/node_modules/next/dist/build/webpack/require-hook.js:96:28)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/jacobwise/Next/partytown-test/node_modules/@builder.io/partytown/react/index.cjs:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jacobwise/Next/partytown-test/node_modules/@builder.io/partytown/react/index.cjs',
    '/Users/jacobwise/Next/partytown-test/.next/server/pages/_document.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/require.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/load-components.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/api-utils.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/next-server.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/next.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/server/lib/start-server.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/cli/next-dev.js',
    '/Users/jacobwise/Next/partytown-test/node_modules/next/dist/bin/next'
  ],
  page: '/'
}`

**Comment by adamdbradley** [comment]
Great, thanks for reporting issue! Should be fixed in the next release: https://github.com/BuilderIO/partytown/commit/8af2ac2758185cb81de3d75a1c18facabac32f09

(I'll also add some sanity checks to make sure the published files are good to go, thanks)

**Comment by adamdbradley** [comment]
https://github.com/BuilderIO/partytown/releases/tag/v0.0.7
