### ISSUE TITLE
Partytown inconsistent behavior depending on how website is hosted

### ISSUE THREAD

**Issue by piotrmilewski** [BuilderIO/partytown#225]
Having Inconsistent behavior with partytown when testing on staging site. Processes 'text/partytown' type tags consistently on localhost, around half the time when using the preview option on gtm for staging site, and never when running staging site normally.

Running partytown using the html integration and when it works it does work correctly (for most gtm scripts, only attached text/partytown to certain scripts)

Partytown version is 0.6.2

Screenshot of behavior on localhost and when running staging using preview option on gtm (when works)
![image](https://user-images.githubusercontent.com/23634963/179809915-878cd490-70ee-4594-a20b-6d46b238313a.png)

Vs screenshot of behavior when just running on staging site
![image](https://user-images.githubusercontent.com/23634963/179810214-716312f3-0337-47cb-ac92-4854881502be.png)

Please let me know if you require any other information and I would be more than happy to assist.

**Comment by adamdbradley** [comment]
This may be because GTM is running scripts in different environment, not that partytown is. Would you be able to provide a repo case?

**Comment by adamdbradley** [comment]
Closing this issue since it has become stale, or has been addressed in recent releases and docs updates. If you feel this is still an issue please reopen a new issue. Thanks.
