### ISSUE TITLE
GTM events issue

### ISSUE THREAD

**Issue by shoppinh** [BuilderIO/partytown#229]
- [ ] I am interested in helping provide a fix!

**Describe the bug**
The error is printed in console and the GTM event is not caught

**To Reproduce**
1. Go to 'https://d2c-a1electroluxjprc-tracka.eluxmkt.com/'
2. Click "Learn more" on any product
3. See error in console tab

**Expected behavior**
The event has to be caught and is listed in GA real-time event summary page 
![image](https://user-images.githubusercontent.com/55548397/180917316-29602877-41e0-481b-8054-6d08d8f65a63.png)

**Partytown version**
0.6.2

**Screenshots**
The error: 
![image](https://user-images.githubusercontent.com/55548397/180917196-e9f0a1cd-9db3-4459-a607-1c234fb2b4e2.png)

**Comment by adamdbradley** [comment]
Sorry I'm not seeing any console log errors and unable to reproduce the issue.

**Comment by shoppinh** [comment]
> Sorry I'm not seeing any console log errors and unable to reproduce the issue.

You have to wait for the page to load for few minutes
