### ISSUE TITLE
Unable to get debug mode working

### ISSUE THREAD

**Issue by omikader** [BuilderIO/partytown#230]
- [x] I am interested in helping provide a fix!

**Describe the bug**
I've enabled debug mode and all forms of logging, but I don't see anything appearing in the console

**To Reproduce**

1. Set partytown config in `index.html`

```
    <!-- Partytown config -->
    <script>
      window.partytown = {
        debug: true,
        logCalls: true,
        logGetters: true,
        logSetters: true,
        logImageRequests: true,
        logScriptExecution: true,
        logSendBeaconRequests: true,
        logStackTraces: true,
        forward: ["zE"],
      };
    </script>
    <script src="%PUBLIC_URL%/~partytown/partytown.js"></script>
```

2. Build and load page

**Expected behavior**
I expected to see logs in console, similar to what is shown in the [docs](https://partytown.builder.io/debugging)

**Partytown version**
0.6.2

**Screenshots**
Chrome console isn't showing any partytown logs (pretty sure the error is unrelated -- it happens in local development, even when partytown is disabled)

![image](https://user-images.githubusercontent.com/16735699/181132491-15535824-5420-4e8b-bec4-ad9190da50ed.png)

I added a breakpoint and saw that the values I've provided are definitely passed through to the partytown script, but I'm unsure why it is not working.

![image](https://user-images.githubusercontent.com/16735699/181131934-782a4df2-b7a1-473a-921b-a57e8b5ef567.png)

**Comment by sylvain-a** [comment]
Hi @omikader , can you check your "Default levels" in the Dev Tools ? You may have to switch "Verbose" to see the logs in the console...

**Comment by omikader** [comment]
🤦‍♂️ that was it, thanks

**Comment by cipriancaba** [comment]
I was going crazy over this, thanks @sylvain-a

**Comment by gkTim** [comment]
Also had this problem. Maybe when debug is set to true print a warning message that log level verbose needs to be set to show the logs?
