### ISSUE TITLE
2cfzzdpbipn.d not found

### ISSUE THREAD

**Issue by vasilyeu-pavel** [BuilderIO/partytown#231]
- [ ] I am interested in helping provide a fix!

**Describe the bug**
When I'm opening website in two browser's tab, in the first tab I get a lot of errors and events aren't sending.
**2cfzzdpbipn.d not found**

**To Reproduce**
1. Load page with partytown
2. Open another tab with the same domain
3. See error

**Partytown version**
`0.6.2`

**Comment by adamdbradley** [comment]
I'm unable to reproduce the error with these steps. Would you be able to provide a reproduction case?
