### ISSUE TITLE
'Event.path' is deprecated and will be removed in M109, around January 2023.

### ISSUE THREAD

**Issue by mbogunovic** [BuilderIO/partytown#233]
'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details.
![image](https://user-images.githubusercontent.com/31932991/181305771-eec88358-5bbc-4abd-96d3-8695d9bd6080.png)

When running google audit, I get this warning, maybe it's good to know since January 2023 is not that far

**Comment by Robjmzbaubap** [comment]
Any updates on this?

**Comment by jbryan1112** [comment]
bump

**Comment by mbogunovic** [comment]
@adamdbradley @jbryan1112 Can be fixed and merged easily if someone has time for this... Lately I've been too busy to make a PR

**Comment by that-joao** [comment]
Sorry for commenting in a closed issue but I'm still seeing the exact same warning after updating, wondering if anyone is experiencing it as well.

**Comment by Robjmzbaubap** [comment]
I am also experiencing the same issue after updating:
```
`Event.path` is deprecated and will be removed. Please use `Event.composedPath()` instead.
```

**Comment by duffner** [comment]
Should we open a new issue?
