### ISSUE TITLE
Documentation on how to sandbox DOM access?

### ISSUE THREAD

**Issue by JamesNJep** [BuilderIO/partytown#238]
Reading about Partytown I though it had said it could sandbox thirdparty scripts access to the page. But looking through the config options I couldn't find any options for restricting DOM access. 

As an example if I had form asking for Name, Age, and Email, and a third party script for validation email addresses, and only wanted the third party script to be able to have access to the Email field on the form. Could I configure Partytown to only allow access to the one field?

**Comment by westonruter** [comment]
I'm working on documentation for this. Probably first in blog post form.

**Comment by westonruter** [comment]
@JamesNJep I just blogged a writeup: [Sandboxing with Partytown](https://weston.ruter.net/2022/11/30/sandboxing-with-partytown/)

**Comment by adamdbradley** [comment]
Closing this issue since it has become stale, or has been addressed in recent releases and docs updates. If you feel this is still an issue please reopen a new issue. Thanks.
