### ISSUE TITLE
Running scripts injected by GTM without a url on main thread

### ISSUE THREAD

**Issue by habiiev** [BuilderIO/partytown#244]
There is a script that is loaded using google tag manager that we would like to run on a main thread, while keeping other scripts working using partytown.

To load it a script is injected into the html that sets a config property on `window` and then creates a new `<script>` tag with a url. I've added the url of the script to `loadScriptsOnMainThread` and the script that is loaded from the url is working on the main thread, which is what we want, but the first script, directly injected by gtm, is still created with `text/partytown`.

So the problem is that for the second script with url to work, the first script needs to set config on window, which it sets in the web worker, and the script that is ran on the main thread does not have access to it.

So my question is if there is a way to run a single script (without a url) injected by gtm on the main thread?

The first script basically does this:

```javascript
window.lib_config = {/* some config in here */};
var a = f.createElement("script");
a.async = !0;
a.type = "text/javascript";
a.src = /* lib url */;
f.head.appendChild(a);
```

**Comment by mhevery** [comment]
Please look into `loadScriptsOnMainThread` https://partytown.builder.io/configuration. I believe that is what you are looking for. If you think the docs are not clear enough, we would love a doc-fix PR.

**Comment by habiiev** [comment]
The feature I needed was just released yesterday! Thank you so much 😸

**Comment by teunissenstefan** [comment]
@habiiev has this actually worked for you? I have the following script that is loaded from GTM to get the scroll percentage:
```
<script id="script-scrollboi-test" type="text/javascript">
document.addEventListener('scroll', function() {
  var h = document.documentElement,
    b = document.body,
    st = 'scrollTop',
    sh = 'scrollHeight';

var percent = (h[st]||b[st]) / ((h[sh]||b[sh]) - h.clientHeight) * 100;
    console.log(percent);
});
</script>
```
And this in the config:
`loadScriptsOnMainThread: ['script-scrollboi-test']`

No matter what I try, the script keeps getting the "text/partytown-x" type which seems to prevent it from working. When adding the script manually to the DOM it does work.

**Comment by habiiev** [comment]
@teunissenstefan I'm sorry, but I left the company where we had that problem

I know that the team created a patch for the partytown, but I don't know the details, sorry 😅

**Comment by teunissenstefan** [comment]
Ah understandable. Don't worry about it. Thanks for letting me know!

**Comment by michaelbourne** [comment]
@teunissenstefan it appears to only work via URL, not ID like documented. I still haven't found the cause of the error, typescript isn't my forte.
