### ISSUE TITLE
Partytown tries to turn an `image/gif` response into a function

### ISSUE THREAD

**Issue by ricardokojo** [BuilderIO/partytown#245]
- [x] I am interested in helping provide a fix!

**Describe the bug**
I've stumbled upon [this issue](https://github.com/BuilderIO/partytown/issues/51) because we had the same problem.

Debugging it, we've discovered that the problem is that `https://googleads.g.doubleclick.net/pagead/viewthroughconversion/${SOME_NUMBER_ID}/` returns (after some redirects) a GIF.

Partytown tries to wrap it in an anonymous function, which generates the error message.

**To Reproduce**
1. Have a `doubleclick` as a Partytown script;
2. Open your webpage;
3. The error should be in the browser's console.

**Reproduction link**
I don't know how to reproduce it in a sandbox, as this script is added via GTM and I'm not lectured in Google platforms (Analytics, Ads, Tag Manager etc).

**Expected behavior**
Partytown **should not** try to run every response as Javascript, as it's possible to check the `content-type` response header

**Partytown version**
`0.6.4`

**Screenshots**
![image](https://user-images.githubusercontent.com/29009138/186525481-3dfaa4ce-e180-42b4-b4a5-1159822c2d7d.png)

:point_up: Error shown in the console.

![image](https://user-images.githubusercontent.com/29009138/186525610-7115a6ab-f863-4e75-bfdd-5327a1ae1ebb.png)

:point_up: Source code of the function that Partytown generated.

**Additional context**
Investigating the source files, we found that the error lies at `receiveMessageFromSandboxToWorker` arrow function from `partytown-ww-sw.js`.

Further down this block, it is possible to check the `content-type` of the response (`rsp` variable). However, I'm not exactly sure where to check it and which MIME-types to consider.

cc @leocwolter, who helped me debug
cc @orballo, who created the original issue (and might find this relevant)

**Comment by leocwolter** [comment]
Some other observations:

- This probably occurs everytime a script added to partytown (in our case an Google Adsense script added through GTM) does a request which has a content-type different from `text/javascript`;
- The log appears to be printed by a [`console.error` in a `catch` statement](https://github.com/BuilderIO/partytown/blob/f6d330337014eea4c0a5e2e83d0ee7197cefd770/src/lib/web-worker/worker-exec.ts#L53) so it should NOT have any effect on the behaviour of other scripts. Besides that it is still a false positive that should not be printed to the console.

**Comment by mhevery** [comment]
@leocwolter thank you for the PR fix!

**Comment by orballo** [comment]
Oh, that's nice! I left the project where I was working with `partytown` so I couldn't find time to debug and figure out what was happening.

I'm glad you found a fix! Thanks @ricardokojo and @leocwolter! :D
