### ISSUE TITLE
CORS issues 

### ISSUE THREAD

**Issue by andrewgadziksonos** [BuilderIO/partytown#25]
First off, I'm so excited for this project 🚀  great work so far 🔥 

I wanted to report some CORS errors I'm seeing in my application,

```
partytown-ww-sw.js:333 Access to XMLHttpRequest at 'https://4273294.fls.doubleclick.net/activityi;src=4273294;type=sonos035;cat=sonos00h;ord=4456809462774;gtm=2wg9r0;auiddc=855366606.1630431318;~oref=http%3A%2F%2Flocalhost%3A3000%2Fen-us%2Fhome?' (redirected from 'http://4273294.fls.doubleclick.net/activityi;src=4273294;type=sonos035;cat=sonos00h;ord=4456809462774;gtm=2wg9r0;auiddc=855366606.1630431318;~oref=http%3A%2F%2Flocalhost%3A3000%2Fen-us%2Fhome?') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

This is the invoking code that triggers the error,

```
, gc = function(a, b) {
        var c = H.createElement("iframe");
        c.height = "0";
        c.width = "0";
        c.style.display = "none";
        c.style.visibility = "hidden";
        var d = H.body && H.body.lastChild || H.body || H.head;
        d.parentNode.insertBefore(c, d);
        cc(c, b);
        void 0 !== a && (c.src = a); // CORS error is reported here
        return c
```

![image](https://user-images.githubusercontent.com/31038519/136089766-7542103a-87df-4930-a35d-91b73a533118.png)

This is what I see in the DOM 

![image](https://user-images.githubusercontent.com/31038519/136090159-d9915d41-f12e-4499-9fa0-a0a8c95a6a1d.png)

**Comment by adamdbradley** [comment]
Would you be able to submit a PR that adds this scenario as a test? https://github.com/BuilderIO/partytown/tree/main/tests/integrations

If you can copy this file https://github.com/BuilderIO/partytown/blob/main/tests/integrations/gtm/index.html and recreate the error with the smallest amount of code that'd help us narrow it down and add more tests around it. 

Thanks!

**Comment by geekysaurabh001** [comment]
It's the same/similar issue I am facing but in the NextJS 13. It just doesn't work. GA4 using GTM has no CORS setting and nowhere in either partytown or nextjs docs it showcases how to go about "proxying-requests" here which works.

**Comment by bnonn** [comment]
I'm having the same problem using GTM.

**Comment by kevinstark86** [comment]
Not being able to use GTM with Partytown in NextJS seems like a massive oversight. Do you know if anyone has this working in NextJS yet?

**Comment by yurasytnyk** [comment]
steps to reproduce

Create gtm

Bootstrap Next.js project (right now I get it working with app router not pages)

Install partytown library npm install "@builder.io/partytown"

open root layout file

use next code

```
export default function RootLayout({ children }: { children: React.ReactNode }) {
return (
<html lang="en">
<Partytown debug={true} forward={["dataLayer.push"]} />
<script
id="gtm"
type="text/partytown"
dangerouslySetInnerHTML={{
__html: \(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='[https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)](https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f));})(window,document,'script','dataLayer','PASTE-HERE-YOUR-GTM-ID');`,}}/><body className={inter.className}>{children}<noscript><iframesrc="https://www.googletagmanager.com/ns.html?id=1. PASTE-HERE-YOUR-GTM-ID"height="0"width="0"className="hidden"/></noscript></body></html>);}`
```
