### ISSUE TITLE
Ga4 No incident was reported.

### ISSUE THREAD

**Issue by victorykong** [BuilderIO/partytown#256]
- [ ] I am interested in helping provide a fix!

**Describe the bug**

**To Reproduce**

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**

**Partytown version**
What version of Partytown you are using, e.g. `0.0.1`
    "@builder.io/partytown": "^0.7.0",

**Screenshots**
<img width="784" alt="image" src="https://user-images.githubusercontent.com/50655436/191242280-06c078e1-c14a-4db3-8b94-82c0e3232d3c.png">
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/50655436/191242337-22f0541a-090b-436e-8f51-912b95604813.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/50655436/191242386-85372556-5a1d-4adf-860d-4034392e36df.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/50655436/191242440-b258a4ee-7976-4d3b-a758-b063e7bb0056.png">

**Additional context**

**Comment by adamdbradley** [comment]
Closing this issue since it has become stale, or has been addressed in recent releases and docs updates. If you feel this is still an issue please reopen a new issue. Thanks.
