### ISSUE TITLE
The variable on the access window is undefined.

### ISSUE THREAD

**Issue by victorykong** [BuilderIO/partytown#260]
- [ ] I am interested in helping provide a fix!

**Describe the bug**
The variable string/number/boolean on window is accessed normally, and accessing the variable of type object will return undefined.

**To Reproduce**
None.

**Reproduction link**
Unable to create demo due to limitation of partytown script.

**Expected behavior**
As the document says, you can access the values on the window arbitrarily.

**Partytown version**
0.7.0

**Screenshots**
<img width="711" alt="image" src="https://user-images.githubusercontent.com/50655436/191927750-ab6d6a70-3543-410a-9349-85094e861d45.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/50655436/191927774-2e404b62-bd0f-4215-a67e-cde647ba14f0.png">
<img width="695" alt="image" src="https://user-images.githubusercontent.com/50655436/191927821-fbf60784-3c46-41d1-819b-5e3920cb416e.png">

**Additional context**

**Comment by victorykong** [comment]
@adamdbradley Please tell me how to change it.Thanks.

**Comment by Girilloid** [comment]
Global fields from main window are n ot accessible from worker bty default. There is not documented config property `mainWindowAccessors` which allows you to access such a fields from sandboxed script. See this [test](https://github.com/BuilderIO/partytown/blob/main/tests/integrations/main-window-accessors/index.html) for example usage. hosted test is available [here](https://partytown.builder.io/tests/integrations/main-window-accessors/).

**Comment by victorykong** [comment]
Thank you very much for solving it, but this part of the description seems to have never appeared in the document; I've debugged this part of the source code, but I'm not familiar with it, so I don't know about $config$. After that, I'll pay more attention.
