### ISSUE TITLE
Can't forward __adroll

### ISSUE THREAD

**Issue by DzmVasileusky** [BuilderIO/partytown#262]
- [ ] I am interested in helping provide a fix!

**Describe the bug**
We are loading adroll with partytown.
First adroll script is
```
window.__adroll||(function(){...}
```
Later it tries to access `__adroll` in another script which is also in a web-worker like this
```
__adroll.set_consent(...);
```

`__adroll` is undefined in the second code sample.

I've tried to forward it like this
```
forward: ['__adroll']
```
but it is not solving an issue.
It seems like patrytown is forwarding `__adroll` to the global window but not to other workers which makes multi script libraries to fail.

**Expected behavior**
Forwarded properties should be accessible in every worker
OR
A possibility to call connected scripts in the same worker making scope shared for them

**Partytown version**
`0.6.4`

**Screenshots**
<img width="966" src="https://user-images.githubusercontent.com/10651174/192001098-5342d977-1340-4c1f-8236-e5c54cf03b8b.png">

**Comment by Girilloid** [comment]
Have you tried to use [`globalFns`](https://github.com/BuilderIO/partytown/blob/main/src/lib/types.ts#L427) config property?

**Comment by DzmVasileusky** [comment]
Ok, that's what helped `forward: ['__adroll', '__adroll.set_consent']`
