### ISSUE TITLE
Make `loadScriptsOnMainThread` accept regexp or substrings

### ISSUE THREAD

**Issue by DzmVasileusky** [BuilderIO/partytown#263]
**Is your feature request related to a problem? Please describe.**
Current `loadScriptsOnMainThread` implementation requires 100% match to the url.
But sometimes url is dynamic:
- it can have different protocols
- it can use reverse proxy
- it can have dynamic query string
- we can have multiple 3rd party scripts and want to block all of them by a domain name or pattern

**Describe the solution you'd like**
`loadScriptsOnMainThread` should accept a substring or regexp to allow it working with dynamic / multiple urls

**Comment by itxchh** [comment]
I'd be happy to try implementing this :)

**Comment by ramirezcgn** [comment]
I need this feature too.

**Comment by gerardo-rodriguez** [comment]
This would be very helpful, thank you! 🙂

**Comment by gioboa** [comment]
Closed by #520
