### ISSUE TITLE
Cannot read properties of undefined (reading '$location$')

### ISSUE THREAD

**Issue by DzmVasileusky** [BuilderIO/partytown#265]
- [x] I am interested in helping provide a fix!

**Describe the bug**
Partytown is causing sometimes an error:
```
partytown-ww-sw.js?v=0.6.4:1721 Uncaught TypeError: Cannot read properties of undefined (reading '$location$')
    at receiveMessageFromSandboxToWorker (partytown-ww-sw.js?v=0.6.4:1721:21)
```

This is the line causing the error
```
env.$location$.href = msgValue.url;
```

**Partytown version**
0.6.4

**Screenshots**
<img width="722" alt="Снимок экрана 2022-09-26 в 19 01 52" src="https://user-images.githubusercontent.com/10651174/192325374-d60266ac-0834-4487-9aa1-3fc9182a885f.png">

**Comment by 0x15f** [comment]
Also seeing this error randomly in production with Shopify Hydrogen, no clear steps to replicate. Appears to be a race condition or something similar.

**Comment by DzmVasileusky** [comment]
Sometimes `msgType` 13 is coming before `msgType` 5. Proceeding investigation

**Comment by DzmVasileusky** [comment]
So yeah, I have debugged a little bit more and find out that send messages sequence do not guarantee same received messages sequence.

<img width="1423" alt="Снимок экрана 2022-11-10 в 17 40 34" src="https://user-images.githubusercontent.com/10651174/201121761-fbc30008-bbd5-4137-bf59-04662aae5273.png">


`setTimeout` isn't helping here as well. It seem to just decrease amount or errors
```
            const onLocationChange = (type, state, newUrl, oldUrl) => {
                setTimeout((() => {
                    console.trace('VAS 13');
                    worker.postMessage([ 13, {
                        $winId$: $winId$,
                        type: type,
                        state: state,
                        url: doc.baseURI,
                        newUrl: newUrl,
                        oldUrl: oldUrl
                    } ]);
                }));
            };
```
