### ISSUE TITLE
sending all dataLayer properties from the worker thread to the main

### ISSUE THREAD

**Issue by oyilmaztekin** [BuilderIO/partytown#27]
I have been trying to understand how partytown handles the dataLayer event and possible pitfalls we might encounter in the future. There is an application written with Next.js, and I have the intention to test partytown in our test environments. However, there is a blind spot for me that I want to clarify.

1. I have added the google tag manager in our next application using with `GoogleTagManager ` and also `Partytown` ✅ 
```js
  <GoogleTagManager containerId={gtmID} forward={['dataLayer.push']} />  
  <Partytown forward={[['dataLayer', 1]]} />
```
2. I have been observing datalayer events with an extension which is  [Adswerve - dataLayer Inspector+](https://chrome.google.com/webstore/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom), and I can say that it works well for now according to the console activity. ✅   
4. Now, I want to access datalayer properties as global variables within the main thread because many things depend on it. According to the code I shared above, I couldn't push or catch these data under the main window.

What is the correct way to accomplish that?

In addition, with this config above dataLayer events are not sent to the cloud tag manager.

**Comment by adamdbradley** [comment]
Thanks for the tip about dataLayer Inspector+, I'll start using that too.

Which dataLayer properties do you want to access from the main thread? If you can help me define what it needs to do we can work out some tests and update the code to make sure we can cover all the cases, or at least try. Thanks.

**Comment by oyilmaztekin** [comment]
Thanks for the reply.  More accurately, I want to access some data of dataLayer from the main thread, created and filled inside partytown's worker. Actually, it is about creating communication between partytown's workers and the main thread. You already have messaging events.  After every data change, partytown sends serialized data to the main thread.  We can write our handler and catch these data, but I am searching for a more straightforward solution if possible, such as using `forward` prop, etc...    

However, accessing dataLayer properties like functions, objects, etc... from the main thread is not intended. For example, DataLayer is an array filled by our functions inside the partytown's worker, but we can't access these data from the main thread. Some other third-party scripts depend on these data stored into datalayer, and these third parties work in another thread.  

If you need an assist to clarify the situation, I can gladly help.

**Comment by WebRom1145** [comment]
Is there already a solution for this? I have exactly the same problem.I want to update variables from the web worker in the main thread
