### ISSUE TITLE
[Bug] NodeList is not implemented

### ISSUE THREAD

**Issue by itxch** [BuilderIO/partytown#271]
- [x] I am interested in helping provide a fix! ✅ 

**Describe the bug**
EDIT: Seems like the issue is that NodeList is not implemented in the webworker context, so its complaining because NodeList is undefined.

~~`AnyHTMLElement instanceof NodeList` throw a TypeError: Right-hand side of 'instanceof' is not an object.
However doing `AnyHTMLElement instanceof Node` or `AnyHTMLElement instanceof Array`, etc works.~~

**To Reproduce**
1. Open web server https://lively-cherry-338.fly.dev/
2. Open console - see the error.

**Reproduction link**
- Repo: https://github.com/itxchh/partytown-nodelist-issue
   - To reproduce locally, clone and run `npx http-server .`.
- Link: https://lively-cherry-338.fly.dev/

**Expected behavior**
1. It should not throw a TypeError.
2. It should log `isNodeList false` to the console.

**Partytown version**
v0.7.0 (latest at time of writing)

**Screenshots**
![CleanShot 2022-10-01 at 16 14 06](https://user-images.githubusercontent.com/54910400/193416100-4e32595f-c46f-4492-ad2a-f962174feab5.png)

**Comment by itxchh** [comment]
After _actually reading the error message_ and trying to log out `NodeList` - seems like the issue is that NodeList is not implemented in the webworker context

**Comment by mhevery** [comment]
Beautiful repro. Seems like you are interested in helping solve this issue. Let us know if you need any help.

**Comment by itxch** [comment]
@mhevery fix here: https://github.com/BuilderIO/partytown/pull/272
Lemme know if any changes required etc?
