### ISSUE TITLE
Event.Path Deprecated: Use Event.composedPath Instead:  Web.Dev penalty 

### ISSUE THREAD

**Issue by duffner** [BuilderIO/partytown#284]
Issue: Warnings for web.dev / Google - 'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details.

Your reproduction must have these:
1. Install GatsbyJS 
2. Install PartyTown
3. Use Atomics via Cross-Origin Headers 
4. Configure GA4 leveraging PartyTown 
5. Run Lightspeed / Web.dev test 
6. See the error about the event.path 

**Expected behavior**
No Warning from Web.dev 

**Partytown version**
0.71 

**Screenshots**
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/7387019/196302743-3d313b8b-9d1c-42de-9eec-a076bac06eba.png">

**Additional context**
Important Note:  I've tested without Atomics and got the same error via #233.  According to this note, #269 was supposed to solve this issue but it does not.  Unfortunately, I'm too new to Party Town to even know where to begin on providing a patch, but I'm hopefully someone much smarter than me and able to help, as the site I'm working on had all 100 web.dev scores until this issue appeared.

**Comment by duffner** [comment]
@nicksrandall, are you able to take a look at this one?   I see you referenced 233 supposed to fix this issue, but it doesn't appear to have worked as expected.

**Comment by CesarBenavides777** [comment]
@duffner @nicksrandall if it helps, this comes into play when pulling in google tag manager like this on Next js, but similar implementation also triggers error on gatsby:

````
import Script from "next/script";

<Script
        id="gtag-base"
        strategy="worker"
        dangerouslySetInnerHTML={{
          __html: `
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer', '${GTM_ID}');
          `,
        }}
      />
````

**Comment by duffner** [comment]
```import React, { Fragment } from 'react';
import { Script } from 'gatsby';

const RootElement = ({ children }) => {
  return (
    <Fragment>
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GATSBY_GA_MEASUREMENT_ID}`}
        strategy="off-main-thread"
        forward={[`gtag`]}
      />
      <Script
        id="gtag-config"
        strategy="off-main-thread"
        dangerouslySetInnerHTML={{
          __html: `window.dataLayer = window.dataLayer || [];
          window.gtag = function gtag(){ window.dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${process.env.GATSBY_GA_MEASUREMENT_ID}', { send_page_view: false })`
        }}
      />
      <div>{children}</div>
    </Fragment>
  );
};

export default RootElement;
```

@CesarBenavides777, yes I'm doing almost the exact same as you.  As seen above, hope this helps @nicksrandall.

**Comment by CesarBenavides777** [comment]
@duffner No nothing so far :/

**Comment by Robjmzbaubap** [comment]
Are there any news on this issue or is there any way I can help to solve this?

Our site is penalyzed only by this 💀 

```
`Event.path` is deprecated and will be removed. Please use `Event.composedPath()` instead.
```

![Screen Shot 2022-12-16 at 12 07 37](https://user-images.githubusercontent.com/106095235/208161607-416e0030-6a75-4ac7-86f8-810658bd7ad8.png)
![Screen Shot 2022-12-16 at 12 07 46](https://user-images.githubusercontent.com/106095235/208161612-273fc7c3-26e4-4d71-b027-7cfebc1050c9.png)

**Comment by nicksrandall** [comment]
I'm sure the maintainers here would happily accept a PR if any of you wanted to submit fix for this issue. I am currently unable to look into this.

**Comment by BuslikDrev** [comment]
```
			var setting = {'name': 'name'}a;
			var setting2 = {'name': 'name2'};

			var func = function(setting) {
				console.log(setting);
				if (!('composedPath' in setting)) {
					console.log(setting);
					var setting2 = {'name': 'name2'};
					var i;
					for (i in setting) {
						if (i == 'name') {
							setting2['name'] = setting['name'];
						}
						setting2[i] = setting[i];
					}
				}
			}

			func(setting);
			window.addEventListener('load', func, {once:true, passive:true});
```

Если хотите функцию вызвать с возможностью указания настроек и через window.addEventListener() без дополнительной обвёртки function() {func(setting);}
то устанавливайте проверку, чтобы массив данных не содержал if (!('composedPath' in setting)) {) - это будет означать, что никаких данных не поступило.

**Comment by duffner** [comment]
@adamdbradley, I'm on version 0.7.4, and this is not resolved.  Is this the correct version that contains the fix?
