### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'E')     at Ze

### ISSUE THREAD

**Issue by lukovskij** [BuilderIO/partytown#286]
Hello!
I implemented partytown integration via 'partytownSnippet'.
After integration and release I get this issue in console:
"Uncaught TypeError: Cannot read properties of undefined (reading 'E')     at Ze"

**Comment by adamdbradley** [comment]
Thank you for opening the issue. To help us debug this further, would you be able to provide a way to replicate this? Creating a PR, with the minimal amount of code to re-create the issue would help us debug. A good example to emulate is the Google Tag Manager test: https://github.com/BuilderIO/partytown/tree/main/tests/integrations/gtm

Some more information can be found here: https://github.com/BuilderIO/partytown/blob/main/DEVELOPER.md#submitting-issues-and-writing-tests

Thank you for your help!
