### ISSUE TITLE
Proxy calls to `localStorage.getItem()` for sandboxing and ensuring value is current

### ISSUE THREAD

**Issue by westonruter** [BuilderIO/partytown#293]
**Is your feature request related to a problem? Please describe.**

I was experimenting with sandboxing a script to block access to `localStorage`, but I found that this was not currently possible. Namely I configured Partytown as follows:

```js
var partytown = {
    apply: (opts) => {
        console.log('apply:', opts.name);
        if (opts.constructor === 'Window' && opts.name.startsWith('localStorage.')) {
            return opts.prevent;
        }
        return opts.continue;
    }
};
```

I then had this script on the page:

```html
<script type="text/partytown">
localStorage.setItem('greeting', 'Hello World');
console.info(localStorage.getItem('greeting'));
localStorage.removeItem('greeting');
localStorage.clear();
</script>
```

In the console I then see only these calls logged out:

```
apply: localStorage.setItem
apply: localStorage.removeItem
apply: localStorage.clear
```

The call to `localStorage.getItem` is missing. This appears to have been done intentionally, as the entire `localStorage` data is sent to the worker when it is initialized:

https://github.com/BuilderIO/partytown/blob/ab532e6ed6586bee30072a80d7379ac7d3eae240/src/lib/sandbox/read-main-platform.ts#L74-L81

The initially-synced value is then referred referenced locally instead of invoking `callMethod` to obtain the value from the main thread:

https://github.com/BuilderIO/partytown/blob/4740ceab5fee438c513136c91447ae5eb2211725/src/lib/web-worker/worker-storage.ts#L24-L42

Was this done for the sake of performance? 

As it stands right now, it is quite possible for the storage in the worker to get out of sync with the storage in the main thread. If the main thread calls `localStorage.setItem()` after the worker is initialized, the stored value is not seen in the worker. There would seem at least a need to add a `storage` event listener on the main thread and continuously sync changes back to the copy in the worker. Nevertheless, this could be avoided if calls to `localStorage.getItem()` were proxied. This would also eliminate duplication of the `localStorage` data, reducing memory usage (although at the cost of slower execution time).

**Describe the solution you'd like**

Discontinue sending the entire `localStorage` and `sessionStorage` datasets into the worker at initialization, and instead proxy all calls to `getItem` to obtain the canonical current value from the main thread.

**Comment by n0th1ng-else** [comment]
Hey any update on this issue? I find it makes a lot of sense, considering we can control the cookies, I wonder what is the reason to leave localStorage untracked?

**Comment by gioboa** [comment]
Hi @n0th1ng-else I didn't look at this issue. would you like to drop a PR for that?
