### ISSUE TITLE
Add nonce to Partytown script for Content Security Policy

### ISSUE THREAD

**Issue by nicolaturcato** [BuilderIO/partytown#299]
**Is your feature request related to a problem? Please describe.**
I have a problem while trying to use Partytown React component. I have a Content Security Policy set that prevents injecting inline scripts unless they have a `nonce`. Issue that appears is: "Refused to execute inline script because it violates the following content security policy directive".
In order to solve this problem I had to load the script from `@builder.io/partytown/integration` and passing the `nonce` to the script.

**Describe the solution you'd like**
Add "nonce" property to Partytown React component that needs then to be passed to Partytown script.

**Comment by sigginjals** [comment]
Hey @nicolaturcato, How did you manage to propagate the nonce to the scripts executed by Partytown?

**Comment by sigginjals** [comment]
@nicolaturcato Once you fixed that, did the scripts get executed as expected?

**Comment by nicolaturcato** [comment]
@sigginjals yes the `nonce` is passed at that point.
