### ISSUE TITLE
Partytown unable to import into GatsbyJS template

### ISSUE THREAD

**Issue by ewagstaff** [BuilderIO/partytown#3]
Very excited to try out this package. However I've been unable to import the React version into our GatsbyJS-based template, and also unable to use the vanilla script. I've created [a sample project using the basic Gatsby starter page](https://github.com/sfchronicle/partytown-gatsby-test) as a demo.

Reproduction steps:
- [Clone the project](https://github.com/sfchronicle/partytown-gatsby-test)
- `npm i` to install dependencies, including Partytown
- `gatsby develop` to start local dev

./src/components/seo.js has `import { Partytown } from '@builder.io/partytown/react'` at the top, and that should throw a "Module not found" error. If you comment that out, we are including the vanilla script via React Helmet and that will throw a syntax error.

Screenshots of those errors below:
![Screen Shot 2021-09-23 at 2 03 27 PM](https://user-images.githubusercontent.com/2423322/134587320-a3c63672-6ab3-4f8e-9d7b-b73970b06cc9.jpg)
![Screen Shot 2021-09-23 at 2 03 54 PM](https://user-images.githubusercontent.com/2423322/134587329-67a85e0a-202e-425e-b8d5-3f2aef12f5e7.jpg)

I am running the latest Node LTS version (v14).

**Comment by adamdbradley** [comment]
Thanks for the repo! This helped pin point the issue, thanks
