### ISSUE TITLE
Unexpected token '<' when using Next

### ISSUE THREAD

**Issue by lukejacksonn** [BuilderIO/partytown#30]
Hello 👋  this library looks like exactly what we need for a client project and so we decided to give it a try! We are using next so have added the tags described in the documentation to `_document.tsx`.

```js
<GoogleTagManager containerId={"GTM-XXXXXXXX"} />
<Partytown debug={true} />
```

When we run the site we see:

![image](https://user-images.githubusercontent.com/1457604/139433100-2b2b41f6-52a4-4f61-a58c-5ab44b816385.png)

When we follow the link to the file that caused the error we see HTML in the file with a `.js` extension, presumably the opening `<` here is what it is complaining about?

```
<!DOCTYPE html><html lang="en"><head><script>document.currentScript.dataset.ptScript="gtm";!(function(w,p,f,c){c=w[p]=w[p]||{};(c[f]=c[f]||[]).push(["dataLayer",1])})(window,'partytown','forward');</script><script type="text/partytown">
```

I'm almost 100% sure this is something specific to our setup 😅  but I can't for the life of my figure out what it might be. Have you ever seen this before or know what might be going on.

Thank you enormously in advance 🙇‍♂️

**Comment by jacobwise** [comment]
I ran into the same issue. Don't forget to copy the `lib` folder from the npm package to `public/~partytown`

**Comment by lukejacksonn** [comment]
Oh, doh 🤦‍♂️ yep.. I think that page we were seeing was the 404 page generated by Next. Have implemented the copy task in the next config and now it finds the files.

Thanks for your help @jacobwise 🙇‍♂️
