### ISSUE TITLE
Executing scripts added at runtime through partytown

### ISSUE THREAD

**Issue by vasikaranb-nagarro** [BuilderIO/partytown#303]
**Is your feature request related to a problem? Please describe.**
Partytown works fine for scripts that are added in index.html (i.e. with initial load of application). but any script added later during run-time with type as text/partytown is not executed.

**Describe the solution you'd like**
If a script is created with type as text/partytown and attached to document using appendChild in some JS file which is executed later (during run-time), the same needs to be captured and executed by partytown. 

**Additional context**
Currently the document.queryselectorall is run only once so the partytown doesnt get the scripts that are added later. Is there a way we push those scripts too to partytown?

**Comment by mhevery** [comment]
Would something like `window.partytown.applyScripts()` function, which could be executed any time to look for a new script and execute them solve your issue?

**Comment by adamdbradley** [comment]
Closed with https://github.com/BuilderIO/partytown/commit/8fce15028c98f0b1ce9835265a9e86a5310bddd8

**Comment by adamdbradley** [comment]
When a new script is appended, be sure to set the `type` property (or attribute) to `text/partytown`, then you can append the scriopt to the dom.

Once it's appended, it won't execute because of the `text/partytown` type attribute. But to notify Partytown that a new script has been added to the document, dispatch a `ptupdate` custom event.

For example:

```
const script = document.createElement('script');
script.type = 'text/partytown';
script.innerHTML = `console.log("New partytown script!")`;
document.head.appendChild(script);

window.dispatchEvent(new CustomEvent('ptupdate'));
```

Hope that helps, thanks

**Comment by adamdbradley** [comment]
https://partytown.builder.io/partytown-scripts#dynamically-appending-scripts
