### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by yusuf-saydullayev** [BuilderIO/partytown#326]
yarn add --dev @builder.io/partytown
ParserError:
Line |
   1 |   yarn add --dev @builder.io/partytown
     |                  ~~~~~~~~
     | The splatting operator '@' cannot be used to reference variables in an expression.
     | '@builder' can be used only as an argument to a command. To reference variables in an
     | expression use '$builder'.

**Comment by yusuf591-cpu** [comment]
Solved: I'm used to install packege with powershell. Use another command prompt
![powershell bug](https://user-images.githubusercontent.com/59925798/208291248-2bd2c939-3b8f-4f28-89d1-9214b1b48dc1.png)

**Comment by yusuf591-cpu** [comment]
![cmd](https://user-images.githubusercontent.com/59925798/208291305-93e9f789-c827-404d-9b3a-625f6b6775df.png)
