### ISSUE TITLE
partytownVite not copying lib files to destination

### ISSUE THREAD

**Issue by cesarnml** [BuilderIO/partytown#367]
- [X] I am interested in helping provide a fix!

**Describe the bug**
The [SvelteKit integration guide](https://partytown.builder.io/sveltekit) doesn't work because `partytownVite` does not copy `lib` code to `static/~partytown`.

**To Reproduce**
1. Follow the[SvelteKit integration guide](https://partytown.builder.io/sveltekit) 
2. Deploy to production.
3. Go to production site. 
4. Open Network console and verify that fetching `partytown-sw.js` results in a 404.

**Reproduction link**
https://github.com/cesarnml/partytown-bug/tree/a355b77659232e703cd246a0c908eb8ddf034a0d

**Expected behavior**
I expected `partytownVite` to copy `lib` code to `/static/~partytown/`

**Partytown version**
What version of Partytown you are using, e.g. `0.7.5`

**Screenshots**
<img width="1680" alt="Screenshot 2023-02-13 at 08 46 06" src="https://user-images.githubusercontent.com/26180499/218359269-5a0b05f6-098e-4edb-b256-37591dfc49d2.png">

**Comment by multiplehats** [comment]
Same issue here!
