### ISSUE TITLE
Partytown benchmark is 50 times slower than baseline

### ISSUE THREAD

**Issue by Iceburgino** [BuilderIO/partytown#373]
I see that numbers in partytown benchmark are way in favor of baseline, like it takes 5-10 ms for baseline and 200-500 ms for partytown, atomics on my machine. Is this supposed to be the case?

I'm talking about the one here: https://partytown.builder.io/tests/benchmarks/

**Comment by Iceburgino** [comment]
And my modest benchmark that compares the two paints a better picture. 16-25ms for no partytown and 70-80 for with partytown.

```html
<!DOCTYPE html>
<html>

<body>
  <p id="time"></p>
  <div id="some_id"></div>

  <script src="~partytown/partytown.js"></script>
  <script type="text/partytown">
    let element = document.getElementById("some_id");
    let counter = document.getElementById("time");

    let startTime = performance.now();
    for (let i = 0; i < 10000; i++) {
      let p = document.createElement("p");
      p.innerHTML = "Hello World!";
      element.appendChild(p);
    }
    let endTime = performance.now();

    counter.innerHTML = endTime - startTime;
  </script>

</body>

</html>
```

Would it be an accurate way to compare two cases? And why is the one proposed in the docs slower?

**Comment by adamdbradley** [comment]
When partytown needs to send data between the two threads it takes more time than if it didn't. In many cases the milliseconds shouldn't matter since third-party scripts send data async anyways. However, if the script has a heavy amount of UI updates, like constructing a small app, then Partytown may not be the best fit for that scenario.

**Comment by adamdbradley** [comment]
https://partytown.builder.io/trade-offs#ui-intensive-third-party-scripts
