### ISSUE TITLE
[🐞] Gtag and GTM not working in angular app

### ISSUE THREAD

**Issue by venkatnarasimharao** [BuilderIO/partytown#415]
### Describe the bug

Trying to integrate https://partytown.builder.io/angular to GTM which lazy loads 3rd party scripts with some configurations and by specifying type to type="text/partytown" but it throws this error

GTM script 
```
(function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({
          'gtm.start': new Date().getTime(),
          event: 'gtm.js'
        });
        var f = d.getElementsByTagName(s)[0],
          j = d.createElement(s),
          dl = l != 'dataLayer' ? '&l=' + l : '';
        j.async = true;
        j.src =
          'https://www.googletagmanager.com/gtm.js?id=' + i + dl + '&gtm_auth=xxxxxxxxxxxxxxxxxx&gtm_preview=env-000&gtm_cookies_win=x';
        f.parentNode.insertBefore(j, f);
      })(window, document, 'script', 'dataLayer', 'GTM-XXXXXXX')
```
error below

```
var myDomain=google_tag_manager["GTM-XXXXXXX"].macro(3),site_links=document.getElementsByTagName("a"),target_links=google_tag_manager["GTM-XXXXXXX"].macro(4);Array.prototype.forEach.call(site_links,function(a){for(i=0;i<target_links.length;i++)0>a.href.indexOf(myDomain)&&a.href.includes(target_links[i])&&(a.href+="?_ga\x3d1628004784.1685101889")}); TypeError: Failed to construct 'URL': Invalid URL
    at WorkerBase.get (partytown-ww-sw.js?v=0.8.0:1143:33)
    at eval (eval at run (partytown-ww-sw.js?v=0.8.0:703:9), <anonymous>:3:260)
    at NodeList.forEach (<anonymous>)
    at Proxy.eval (eval at run (partytown-ww-sw.js?v=0.8.0:703:9), <anonymous>:3:194)
    at run (partytown-ww-sw.js?v=0.8.0:703:37)
    at runScriptContent (partytown-ww-sw.js?v=0.8.0:691:13)
    at partytown-ww-sw.js?v=0.8.0:1772:54
    at receiveMessageFromSandboxToWorker (partytown-ww-sw.js?v=0.8.0:1776:19)
```

refer - [76380076/configure partytown](https://stackoverflow.com/questions/76380076/how-to-configure-partytown-builder-for-gtm-in-angular)

### Reproduction

GTM

### Steps to reproduce

following the steps given - [partytown Angular](https://partytown.builder.io/angular)
[example_gtm_partytown_repo](https://github.com/venkatnarasimharao/gtm_partytown)

### Browser Info

Chrome

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction that we can reproduce on our computers. A failing test in our repo or an easily clonable GitHub repo with minimal reproduction steps is needed.
