### ISSUE TITLE
[🐞] Uncaught DOMException error when loaded in iframe

### ISSUE THREAD

**Issue by thdoan** [BuilderIO/partytown#425]
### Describe the bug

When a site with Partytown integration is loaded inside an iframe, it throws this error:

```
Uncaught DOMException: Blocked a frame with origin "https://www.mydomain.com" from accessing a cross-origin frame.
```

### Reproduction

https://web-platform-5d5g5q.stackblitz.io/

### Steps to reproduce

1. Go to the URL above
2. Open console to see error

The https://partytown.builder.io/ iframe has error because it has Partytown integration.

The https://astro.build/ iframe doesn't have error because it doesn't use Partytown.

Is there a way to configure Partytown not to produce this error when the site is loaded inside an iframe?

### Browser Info

Chrome 114

**Comment by mhevery** [comment]
I think you need to configure the `iframe` with cross origin https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
