### ISSUE TITLE
[📖] do we need `partytownSnippet` and `~partytown`?

### ISSUE THREAD

**Issue by benmccann** [BuilderIO/partytown#435]
### Suggestion

https://partytown.builder.io/sveltekit shows including partytown scripts via `partytownSnippet` and copying partytown scripts to `~partytown` where they are served. However, there's no explanation as to what these two different sets of partytown scripts do. Are they both needed or are they doing the same thing? How do the script from `~partytown` get included? I don't see any requests going there and there's nothing else in the guide referencing them. Is there some missing step or does the `partytownSnippet` make a hardcoded request to `/~partytown`?

**Comment by nilanjansiromani** [comment]
You can either of the methods to load partytown
Importing from ~partytown  is preferred as it does not bloat up the html

**Comment by mhevery** [comment]
Closing this issue as
1. it has been answered.
2. It is a question not an actual issue.
