### ISSUE TITLE
How to implement partytown in vanilla js or HTML  project ? Why partytown has most confusing documentation ?

### ISSUE THREAD

**Issue by anishkuls** [BuilderIO/partytown#445]
### Suggestion

Please can anyone tell me step by step how to implement Partytown into vanilla js project? Where is cdn link or where to download partytown.js ? Onsite documentation is so confusing if you are using it for first specially via HTML method.

**Comment by mhevery** [comment]
I am sorry you don't think our documentation is good enough. I think you are looking for https://partytown.builder.io/html and we would love a PR to clarify the documentation.

**Comment by anishkuls** [comment]
Thanks for your reply, maybe your documentation is very great but it not clearly showing the steps to implement partytown to html project !

We have a project based on HTML CSS JS and PHP - and want to use partytown for gtm and goolgle analytics :

so first i tried to find if there is cdn to include partytown.js in to our project but there is nothing like that, so i used :
npm i @builder.io/partytown - this command.

after this D:\npss\node_modules\@builder.io\partytown\lib - inside lib folder i found partytown.js 

so should in include this file to my project if yes then where? and can i include it in head section using scripte tag ?

like this - 

<script>
    partytown = {
      forward: ['dataLayer.push'],
    };
  </script>

<script src="js/partytown.js" type="partytown/js"></script>

??

is this enough to run the project with partytown ?

**Comment by anishkuls** [comment]
@mhevery ,

Supose I have simple project based on HTML like :

my-website/
    -index.html
    css/
        -style.css
        -main.css
    js/
        -myscript.js
    
    so what should be the structure if I am using partytown ?
    
    my-website/
    -index.html
    css/
        -style.css
        -main.css
    js/
        -myscript.js
        -partytown.js
