### ISSUE TITLE
How to integrate partytown with angular?

### ISSUE THREAD

**Issue by ashwinikumar01** [BuilderIO/partytown#45]
@adamdbradley I am trying to connect GTM, Gtag as well as some basic scripts in Angular **index.html**, but seems like they aren't working. 
I am searching for solution but no idea how to implement it.

**GTag Script-**
```
<script type="text/partytown">
  window.dataLayer = window.dataLayer || [];
  function gtag(){
    dataLayer.push(arguments);
  }
  gtag('js', new Date());
</script>
```

**GTM Scripts-**
```   
<script>
      ;(function (w, d, s, l, i) {
        w[l] = w[l] || []
        w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' })
        var f = d.getElementsByTagName(s)[0],
          j = d.createElement(s),
          dl = l != 'dataLayer' ? '&l=' + l : ''
        j.async = true
        j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl
        f.parentNode.insertBefore(j, f)
      })(window, document, 'script', 'dataLayer', 'GTM-ID')
    </script>
```

**Some basic scripts-**
```<script type="text/partytown" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>```
```<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>```

**Comment by ashwinikumar01** [comment]
@adamdbradley Hi, I haven't got any further updates on this issue. Kindly have a look into it and possibly give a way

**Comment by steve8708** [comment]
Hey @ashwinikumar01 - do either of these help?

 https://partytown.builder.io/html
https://partytown.builder.io/trade-offs

**Comment by ashwinikumar01** [comment]
Hi @steve8708, I think a sample repository with angular setup will work as I can already see people are facing problems with integration with angular

**Comment by steve8708** [comment]
Perhaps follow the HTML guide for your angular app and let us know if you hit errors? it should work for angular just like any other html.

And of course contributions welcome, like an angular example like you mention could be a great PR to send if you think it will be valuable to others

**Comment by ashwinikumar01** [comment]
Ok then, let me have a look for the setup with angular

> Hey @ashwinikumar01 - do either of these help?
> 
> https://partytown.builder.io/html https://partytown.builder.io/trade-offs

Thanks @steve8708 for these guides

**Comment by steve8708** [comment]
Great. Also I realized these could be helpful to look at too:

https://twitter.com/JayCooperBell/status/1441828899898331143
https://github.com/BuilderIO/partytown/pull/7

**Comment by adamdbradley** [comment]
Any assistance adding to angular integration docs would be appreciated. It could be a new page similar to https://github.com/BuilderIO/partytown/blob/main/docs/react.md

**Comment by adamdbradley** [comment]
Closing this issue since it has become stale, or has been addressed in recent releases and docs updates. If you feel this is still an issue please reopen a new issue. Thanks.
