### ISSUE TITLE
[🐞] `this` replacing regex is breaking some scripts (Google Analytics via Segment)

### ISSUE THREAD

**Issue by molszanski** [BuilderIO/partytown#452]
### Describe the bug

In [source there is a function that modifies](https://github.com/BuilderIO/partytown/blob/9a5d1ad4177054414fa603ccc8db34bd8ba6b271/src/lib/web-worker/worker-exec.ts#L119-L138) the source of the offloaded script:
https://github.com/BuilderIO/partytown/blob/9a5d1ad4177054414fa603ccc8db34bd8ba6b271/src/lib/web-worker/worker-exec.ts#L119-L132

In some cases it produces an unrunnable code.
Here is a [source](https://cdn.segment.com/next-integrations/actions/google-analytics-4-web/1596841f366e1c6d698c.js) of an analytics code. Prettify it and grep for an object with `dynamicAnchors`

**upd:**
By the power of search I've found the script:
https://github.com/ajv-validator/ajv/blob/master/lib/compile/names.ts

**upd2:** simplest repo / repro in progress

```javascript
// CASE A
// turns this:
n = {
  errors: new o.Name("errors"),
  this: new o.Name("this"),
  self: new o.Name("self"),
}

// into this:
n2 = {
  errors: new o.Name("errors"),
  (thi$(this) ? window : this): new o.Name("(thi$(this)?window:this)"), // problem here
  self: new o.Name("self"),
};

// prob should be:
n3 = {
  errors: new o.Name("errors"),
  this: new o.Name("this"),
  self: new o.Name("self"),
}
// CASE B

// turns this:
b = h.opts.passContext ? n.default.this : n.default.self

// into this:
b = h.opts.passContext ? n.default.(thi$(this) ? window : this) : n.default.self

// prob should be:
b = h.opts.passContext ? n.default."(thi$(this)?window:this)" : n.default.self
// or 
b = h.opts.passContext ? n.default.this : n.default.self
```

### Reproduction

https://stackblitz.com/edit/web-platform-3qzfpd?file=index.html

### Steps to reproduce

Load a script with a source code containing code like that and it will generate a code that JS VM will discard 
https://stackblitz.com/edit/web-platform-3qzfpd?file=index.html

### Browser Info

Chrome

**Comment by mhevery** [comment]
Any chance trying to create a PR for this?

**Comment by molszanski** [comment]
I'll see what I can do!

**Comment by molszanski** [comment]
Fixed with some PRs in October 2023:
https://github.com/BuilderIO/partytown/pull/453
https://github.com/BuilderIO/partytown/pull/473
