### ISSUE TITLE
[🐞] Issue of loading ga4 and fb pixel in react app

### ISSUE THREAD

**Issue by Soumyahoichoi** [BuilderIO/partytown#454]
### Describe the bug

Hey guys, we are using sonar cloud in our project , observing issues on the files generated by running  the party town script.

### Reproduction

the issues ar eappearing in the CI-CD pipeline

### Steps to reproduce

To install the npm package and ran the script of party town and use sonar cloud for code analysis.

### Browser Info

chrome

### Additional Information

use react app, sonar cloud as code analysis tool and try to integrate the party town package.

**Comment by molszanski** [comment]
You mean sonar cloud "complains" that partytown scripts are "bad"? 
I would suggest adding this folder to ignore list and move on

**Comment by Soumyahoichoi** [comment]
We observe that ga4 and facebook pixel are not working in our application.

**Comment by thejackshelton** [comment]
Hey @Soumyahoichoi! Seeing as Sonar Cloud is a paid service, I can't really reproduce it. Could please make a minimal reproduction react app that has this issue? And include any of the errors?

I might be able to help then 😅 

https://partytown.builder.io/faq#will-you-debug-why-my-script-is-not-working-for-me

**Comment by thejackshelton** [comment]
Hey @Soumyahoichoi, I'm going to close this issue following the FAQ from the docs. I'd be happy to take a look at another issue with a minimal reproduction example.
