### ISSUE TITLE
Could partytown be used with visualization libraries? 

### ISSUE THREAD

**Issue by nickchomey** [BuilderIO/partytown#459]
I'm starting to explore the usage of various interactive visualization libraries in my application, but they are somewhat heavy and therefore clog the main thread.

Would partytown (particularly the atomics implementation) be useful in these cases, or would they just have too much going on with tracking/manipulating all the different DOM elements? 

I suppose we could distinguish between crazy force graphs with 3000 nodes and all sorts of physics (eg cytoscape.js, which in particularly interested in) vs more traditional or static visualizations - charts, maps etc such as you'd create with d3js. 

Would it be relevant whether it uses svg vs canvas vs webgl? Eg https://graphaware.com/visualization/2019/09/05/scale-up-your-d3-graph-visualisation-webgl-canvas-with-pixi-js.html (in short, you simply draw pixels to the single canvas Dom element and the js library tracks where they are, vs svg that adds/modifies individual Dom elements for each item) 

I think there could be a lot of potential for something like this, given how commonplace visualizations are becoming and how many people are accessing them on mobile devices with many low-powered CPU cores that are mostly going unused on a webpage. 

Thanks!

**Comment by mhevery** [comment]
Atomics is better, but again use proper RPC channel on top of atomics rather than partytown...
