### ISSUE TITLE
window.visualViewport is not supported

### ISSUE THREAD

**Issue by emilisb** [BuilderIO/partytown#48]
`window.visualViewport` fails with `TypeError: PropCstr is not a constructor`.

Example code:
```html
        <script type="text/partytown">
          (function () {
            console.log('VISUAL VIEWPORT', window.visualViewport);
          })();
        </script>
```

**Comment by adamdbradley** [comment]
Thanks for reporting this issue, we'll get it added: https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport
