### ISSUE TITLE
[🐞] Firefox + Patytown + Astro View Transitions breaking links

### ISSUE THREAD

**Issue by OliverSpeir** [BuilderIO/partytown#486]
### Describe the bug

When using Firefox to view a site with partytown and Astro View Transitions all links break 

Reproduction repo: https://github.com/florian-lefebvre/astro-vt-fallback-bug
Reproduction on deployed site: https://astro-vt-fallback-bug.pages.dev/

- [Partytown breaks VT fallback withastro/astro#8862](https://github.com/withastro/astro/issues/8862)
- Potentially relevant #457 

Best description so far: 

> Using a build of partytown with minification turned off pointed me to a single line.

> <img width="600" alt="image" src="https://github-production-user-asset-6210df.s3.amazonaws.com/69170106/277794924-03cd7409-381e-40f8-928c-1f92e859167a.png">

> Partytown patches the History API, and its code runs whenever the History API is used. It seems like an issue for Firefox to fix, although Partytown may be able to remove this hacky code. Astro's usage of history API is necessary and proper.

> _Originally posted by @lilnasy in https://github.com/withastro/astro/issues/8862#issuecomment-1777981668_

### Reproduction

https://github.com/florian-lefebvre/astro-vt-fallback-bug

### Steps to reproduce

1. Using Firefox browser 
2. Clone reproduction
3. `npm install && npm run dev`
4. Visit localhost:4321 and try clicking top nav links
4. Or visit URL and try clicking top nav links

### Browser Info

Firefox

**Comment by gioboa** [comment]
https://github.com/BuilderIO/partytown/pull/511 closed this one.
