### ISSUE TITLE
[🐞] Partytown breaks in Firefox

### ISSUE THREAD

**Issue by emish89** [BuilderIO/partytown#505]
### Describe the bug

Hi,
I'm using partytown with Astro and seems that in Firefox there is a bug.

It's described all here, even the discussion and minimal example to reproduce:
https://github.com/withastro/astro/issues/8862

Hope you can help solving this `NS_ERROR_NOT_INITIALIZED` issue

### Reproduction

https://github.com/florian-lefebvre/astro-vt-fallback-bug

### Steps to reproduce

https://github.com/withastro/astro/issues/8862

### Browser Info

only Firefox

**Comment by gioboa** [comment]
https://github.com/BuilderIO/partytown/pull/511 closed this one.
