### ISSUE TITLE
[🐞] Google Analytics Events aren't fired

### ISSUE THREAD

**Issue by mrxbox98** [BuilderIO/partytown#519]
### Describe the bug

After setting up Google Analytics with Partytown (user analytics are working) events such as a purchase are not pushed to google analytics.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-heabie?file=src%2Froutes%2F%2Blayout.svelte

### Steps to reproduce

Setup google analytics with partytown properly. 
Push an event like 
```ts
window.gtag("event", "purchase", {
		DATA
	});
```

### Browser Info

All

### Additional Information

When not using Partytown the events are properly pushed.

**Comment by gioboa** [comment]
I see, thanks for your report. Can you create a PR with a failing test for this issue? A vanilla JS one will be perfect.

**Comment by gioboa** [comment]
Did you use [forwarding-events](https://partytown.builder.io/forwarding-events) API ?

**Comment by mrxbox98** [comment]
> Did you use [forwarding-events](https://partytown.builder.io/forwarding-events) API ?

Yes
```tsx
<script>
        // Forward the necessary functions to the web worker layer
        partytown = {
            forward: ['dataLayer.push', 'gtag'],
        };
    </script>
 ```

**Comment by gioboa** [comment]
A specific test for this issue will be awesome to solve this problem

**Comment by lknlknim** [comment]
Did you proxy the url to resolve CORS?

**Comment by mrxbox98** [comment]
> A specific test for this issue will be awesome to solve this problem

Not entirely sure how to write a test for it since I'm unfamiliar with this repo. https://stackblitz.com/edit/sveltejs-kit-template-default-heabie?file=src%2Froutes%2F%2Blayout.svelte should mostly replicate it.

> Did you proxy the url to resolve CORS?

Everything else google analytics works so I don't think its CORS

**Comment by mrxbox98** [comment]
Update: I just received an event in Google Analytics with this config so it might be something else that I have configured incorrectly. I'll give it a week to see what happens.

**Comment by gioboa** [comment]
GA doesn't update data in real-time
You can have more info [here](https://support.google.com/analytics/answer/11198161?hl=en#:~:text=Google%20Analytics%20allows%20for%20a,48%20hours%20in%20an%20account)
