### ISSUE TITLE
[🐞] variables conflict with Splide JS carousel

### ISSUE THREAD

**Issue by maofree** [BuilderIO/partytown#541]
### Describe the bug

Hi
today I tried to integrate partytown on a site with grav cms, but now I'm seeing that there is a conflict problem between the variable n and t also used by another Splide JS script

Could you use variable names other than the overly generic ones that might be used by other scripts?
How do I get around this problem?

![1](https://github.com/BuilderIO/partytown/assets/653230/b9e7abd7-1f44-4f83-aa77-22e532ed45ef)
![2](https://github.com/BuilderIO/partytown/assets/653230/7b2ba2e7-d4c4-4e77-a10b-b85ab390f8cc)

thanks

### Reproduction

is on my local server

### Steps to reproduce

Hi

add
`https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js
https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-intersection@0.2.0/dist/js/splide-extension-intersection.min.js`

and

`const articleProcess = document.querySelectorAll('.article-process .splide');
if (articleProcess.length) {
  for (let i = 0; i < articleProcess.length; i++) {
    new Splide(articleProcess[i], {
      perPage: 3,
      gap: '1rem',
      breakpoints: {
        576: {perPage: 1},
        1199: {perPage: 2},
      },
    }).mount();
  }
}`

### Browser Info

chrome

**Comment by gioboa** [comment]
Hi, these Partytown variables are renamed by the build process. 🤔

**Comment by maofree** [comment]
Is there any way to keep them from changing?

**Comment by gioboa** [comment]
Unfortunately no, but you can use the [debug version](https://partytown.builder.io/distribution#libdebug) of the script if you need a not minified version.

**Comment by maofree** [comment]
thanks for the info

**Comment by gioboa** [comment]
Let me know if it works for you. I close this issue because there is nothing we can do with this specific problem.

**Comment by maofree** [comment]
Hi @gioboa 
I solved it following your advice
using the debug file
with grav cms I also had to rename the ~partytown folder with just partytown and edit the files to remove ~, it couldn't find the js files, I think due to its htaccess
thanks for the support

**Comment by gioboa** [comment]
Nice, great to hear that 🙂
