### ISSUE TITLE
[📖] How can I load partytown from a pure HTML/JS website?

### ISSUE THREAD

**Issue by FANMixco** [BuilderIO/partytown#562]
### Suggestion

I have a website that uses only HTML, CSS and JS. It has no frameworks, no NPM, etc. I want to use party town, but I cannot find any CDN or which file I should load in the <script> tag. Thanks.

**Comment by gioboa** [comment]
You can follow [this guide](https://partytown.builder.io/html) and  you can load the package with services like [unpkg](https://www.unpkg.com/).
In the Partytown library you can find the [compiled scripts](https://www.npmjs.com/package/@builder.io/partytown?activeTab=code) inside lib folder.
