### ISSUE TITLE
Partytown integration with Astro makes over 10'000 proxytown requests on page load[🐞]

### ISSUE THREAD

**Issue by kkopp001** [BuilderIO/partytown#576]
### Describe the bug

I'm using Partytown with Microsoft clarity and when I whenever I add 

`   <script type="text/partytown">
            (function (c, l, a, r, i, t, y) {
                c[a] =
                    c[a] ||
                    function () {
                        (c[a].q = c[a].q || []).push(arguments);
                    };
                t = l.createElement(r);
                t.async = 1;
                t.src = "https://www.clarity.ms/tag/" + i;
                y = l.getElementsByTagName(r)[0];
                y.parentNode.insertBefore(t, y);
            })(window, document, "clarity", "script", "lpr85odovr");
        </script>`

to the <head> it makes over 10'000 Proxytown requests :
![image](https://github.com/BuilderIO/partytown/assets/102523668/03ed06b7-985a-425b-bf05-b2abaa727694)

### Reproduction

staging.layout.ch

### Steps to reproduce

install partytown like that `npx astro add partytown` 

add the clarity script to the head 

`     <script type="text/partytown">
            (function (c, l, a, r, i, t, y) {
                c[a] =
                    c[a] ||
                    function () {
                        (c[a].q = c[a].q || []).push(arguments);
                    };
                t = l.createElement(r);
                t.async = 1;
                t.src = "https://www.clarity.ms/tag/" + i;
                y = l.getElementsByTagName(r)[0];
                y.parentNode.insertBefore(t, y);
            })(window, document, "clarity", "script", "lpr85odovr");
        </script>`

### Browser Info

Chrome

**Comment by macit-emre** [comment]
same here. (i use it inside Google tag manager, and same issue here)
![Screenshot 2024-05-29 at 21 21 16](https://github.com/BuilderIO/partytown/assets/70325326/e32bde38-ac08-4db3-9c98-43d95334c199)

**Comment by waflessnet** [comment]
idem : 

![image](https://github.com/BuilderIO/partytown/assets/6413704/9edd6572-d826-4337-87b4-e609e75fc77f)

**Comment by dsacramone** [comment]
Any solutions here? Does builder.io have any interest in supporting partytown?

**Comment by steve8708** [comment]
`proxytown` is the name of the service worker that allows access across threads (worker and main thread). for scripts that do a lot of dom access, you'll see `proxytown` a lot (sadly we can't hide it from the network tab), but it is not an actual network call, it is just the service worker communication layer. More on that [here](https://partytown.builder.io/trade-offs#intercepted-network-requests)
