### ISSUE TITLE
Does Party Town work with Google Tag Manager preview

### ISSUE THREAD

**Issue by kaheglar** [BuilderIO/partytown#81]
I have Party Town is working with GTM and Analytics, however, when I "Preview" with GTM, it fails to connect. Is this something that _should_ work?

**Comment by Manduro** [comment]
See https://github.com/BuilderIO/partytown/issues/72

**Comment by Shibudubey7** [comment]
I implemented Partytown with Next.js (Page Router), and while I noticed a reduction in Total Blocking Time (TBT), the Tag Manager and Analytics did not trigger. Can you guys help me figure this out?
