### ISSUE TITLE
Partytown discord invite link is invalid

### ISSUE THREAD

**Issue by sidd-oo** [BuilderIO/partytown#92]
Partytown discord invite link is not reachable/valid, Kindly put a new invite link. Make sure to put a permanent link.

> To create a permanent invite, select "never" under "expire after" and "no limit" under "max uses." By doing so, you'll generate a link that has infinite uses and won't become obsolete over any period of time

![image](https://user-images.githubusercontent.com/25115188/156007755-0df5a9c5-49e3-4f6f-a717-6086730d0b2a.png)

**Comment by adamdbradley** [comment]
Thanks, fixed https://github.com/BuilderIO/partytown/commit/d8d04f616dad1e485c0a39824012a8ad66d37f27
