### ISSUE TITLE
Trying to use Partytown on Shopify 2.0 theme

### ISSUE THREAD

**Issue by PHironaka** [BuilderIO/partytown#94]
I'm hoping to use Partytown on Shopify themes moving forward. I understand you guys are working on a Shopify app to make the integration a bit more seamless, but was hoping to get some direction on how to manually configure parytown on a 2.0 Shopify theme.

I've copied all the files from lib folder ( partytown-atomics.js, partytown-media.js, partytown-sw.js) and placed them within the /assets/~partytown/ directory. I placed the inline script in the` <head> `. 

I tried loading a jquery from the assets folder and see the following error when using   <script type="text/partytown" src="/assets/jquery.js"></script>

```
<script type="text/partytown" src="/assets/jquery.js" data-ptid="156465513" data-pterror="TypeError: r.implementation.createHTMLDocument is not a function
    at eval (http://127.0.0.1:9292/assets/jquery.js:4:89469)
    at eval (http://127.0.0.1:9292/assets/jquery.js:4:89569)
    at eval (http://127.0.0.1:9292/assets/jquery.js:4:220)
    at Proxy.eval (http://127.0.0.1:9292/assets/jquery.js:4:225)
    at ge (blob:http://127.0.0.1:9292/c0240a1b-11b4-4bbf-8b01-3ce374a48b93:2:4250)
    at blob:http://127.0.0.1:9292/c0240a1b-11b4-4bbf-8b01-3ce374a48b93:2:16046"></script>
```

Any tips on how to troubleshoot would be appreciated. Thanks!

**Comment by adamdbradley** [comment]
The jquery issue should be fixed as of 0.4.3: https://github.com/BuilderIO/partytown/releases/tag/v0.4.3 

thanks

**Comment by manuelmoreno188** [comment]
Hi @PHironaka I'm also trying to integrate Partytown with Online Store 2.0 themes. Could you provide a guide on how to do this, please? I'd really appreciate it

**Comment by bryanyi** [comment]
Hi @PHironaka and @manuelmoreno188, were you guys able to integrate Partytown with Shopify 2.0? I don't know how PHironaka was able to add /~partytown directory in /assets...when I do and I do a theme deploy, I get an error saying that the /assets directory cannot have subfolders.
