### ISSUE TITLE
Problem with the zone.js (Angular 13)

### ISSUE THREAD

**Issue by jakubsobel** [BuilderIO/partytown#97]
I'm trying to use Partytown with an Angular 13 project, but it looks like the Partytown initialisation fails because of the `zone.js` patching of the `IntersectionObserver` and `MutationObserver`.  

It looks like the Partytown's `getConstructorName` function is returning an empty string for the `IntersectionObserver` and `MutationObserver` when `zone.js` is in use, and that breaks the `mainWindow[cstrName].prototype` line in the `partytown-sandbox-sw.js`.

Minimal reproduction:
https://github.com/jakubsobel/partytown-zonejs-issue
Run using the `ng serve`, go to the `localhost:4200`, you will see the problem in the console:
<img width="1041" alt="Screenshot 2022-03-03 at 12 23 34" src="https://user-images.githubusercontent.com/43335331/156555378-c4d26477-0325-4dcb-939e-184bea8486b7.png">

Uncomment the lines in the `zone-flags.ts` file. That will disable the patching of the `IntersectionObserver` and `MutationObserver`. Run the project again, Partytown will then work correctly.

**Comment by naveedahmed1** [comment]
I am also receiving below error in my Angular App and most probably it's also due to the zone.js:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at partytown-sandbox-sw.html?1651450991258:2:6311
    at Array.map (<anonymous>)
    at _ (partytown-sandbox-sw.html?1651450991258:2:6261)
    at U (partytown-sandbox-sw.html?1651450991258:2:5775)
    at partytown-sandbox-sw.html?1651450991258:2:7417
    at Worker.J.onmessage (partytown-sandbox-sw.html?1651450991258:2:27442)
```

**Comment by naveedahmed1** [comment]
I have verified the changes suggested by @DanteDeRuwe in pull request https://github.com/BuilderIO/partytown/pull/164/files on my local machine and it seems that this fixes this issue. 

Can anyone from the team review and merge this pull request?
