### ISSUE TITLE
need svelte integration 

### ISSUE THREAD

**Issue by MDALIMULALRAZY** [BuilderIO/partytown#99]

**Comment by steve8708** [comment]
hey @MDALIMULALRAZY - take a look at this for how to integrate with svelte https://partytown.builder.io/html

**Comment by outerlook** [comment]
Remember to add `preserve: ['partytown']` to svelte preprocess options on `svelte.config.js` file.
Doing so will tell svelte not to try to preprocess partytown scripts

**Comment by romaindurand** [comment]
@MDALIMULALRAZY I just published a svelte wrapper for partytown : https://www.npmjs.com/package/partytown-sveltekit

I also made a fork of this repo to provide native svelte support but I might need some help on this :sweat_smile: 
https://github.com/romaindurand/partytown/commit/ee08176d082b84f3334e7c85898ceee2054a6963
